### ISSUE TITLE
ICMP packets

### ISSUE THREAD

**Issue by arnemoos** [RoboCup-SPL/Rules#143]
Hi, I ([SPQR] Daniele Affinita) was wondering if according to the rulebook 2023, ICMP packets (such as ping) are considered normal packets, and thus detracted from the available packets.

**Comment by sseering** [comment]
Hi, if this question comes up again: instead of working with ICMP the rules provide for "Team specific debug information" that can be used for the same purpose. This debug information does not count towards the message budget. See Rules section 2.4.2 for details.

No rules document changed are needed.
