### ISSUE TITLE
Shared Autonomy Challenge

### ISSUE THREAD

**Issue by roefer** [RoboCup-SPL/Rules#154]
Two questions about the Shared Autonomy Challenge:

  - Can teams score own goals? If yes, both the attacking and the defending team?
  - According to the regular rulebook, goals do not count if a team exceeds its message budget. What about points for passes?

**Comment by jpha226** [comment]
Regarding own goals: just the defending team can score own goals. The intention is that the attacking team’s goal is essentially not there for scoring purposes (it is of course physically still present so that robots can use it for localization).

In the spirit of the message budget rule, I think it is most appropriate to say that points for passes do not count. That said, I don’t feel strongly about this rule in the context of this challenge and would be open to saying passes can count if others wish to argue for that.

From: roefer ***@***.***>
Date: Friday, May 17, 2024 at 6:08 AM
To: RoboCup-SPL/Rules ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RoboCup-SPL/Rules] Shared Autonomy Challenge (Issue #154)

Two questions about the Shared Autonomy Challenge:
·         Can teams score own goals? If yes, both the attacking and the defending team?
·         According to the regular rulebook, goals do not count if a team exceeds its message budget. What about points for passes?

**Comment by jpha226** [comment]
Closing as clarifications were added to the challenge rules.
