### ISSUE TITLE
Penalty Kick call

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#43]
> 3. For a Penalty Kick: “Foul <color><number>” for the pushing robot, followed by “Penalty Kick <team>”.

For the GameController, it would be much better if the referee just called "Penalty Kick <color> <number>".

**Comment by PatrickGoettsch** [comment]
Solved by #52

**Comment by ahasselbring** [comment]
Sorry, the angled brackets aren't rendered. I meant combining the "Foul" call and the "Penalty Kick" into "Penalty Kick &lt;team&gt; &lt;color&gt;".

**Comment by sseering** [comment]
I like the idea of simpliying the callouts. Though, I am not sure how to understand the last suggestion by Arne H. 

"Penalty Kick <team> <color>" would make me call out ""Penalty Kick HTWK blue" whicht is kinda ambigous. (Did HTWK do the foul? Does HTWK get to kick?)

How about: "Penalty Kick for <team-color-that-kicks> because <offending-teamcolour> <offending-jersey-number>"?

**Comment by ahasselbring** [comment]
Sorry, I'm not concentrated enough. Of course I meant "Penalty Kick &lt;color&gt; &lt;number&gt;", just like Foul is called.

**Comment by PatrickGoettsch** [comment]
So, the penalty kick is called for the fouling team, although the fouled team executes it. This is not how it would be normally called. But you are right the call itself would get easier.

**Comment by PatrickGoettsch** [comment]
So, the penalty kick is called for the fouling team, although the fouled team executes it.

**Comment by ahasselbring** [comment]
If it sounds strange (although the Global Game Stuck rule safely keeps the award for "causing the biggest confusion about on which team to call it and which team gets kick-off"), you can imagine an "against" after "Penalty Kick" :wink:
